name: Docker Image CI

on:
  push:
    branches: [ "1.0.0" ]
  pull_request:
    branches: [ "1.0.0" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          ls 
  docker-compose:
      needs: build
      runs-on: self-hosted
      steps:
      - uses: actions/checkout@v3
      - name: Docker compose for build and run
        run: |
              docker-compose -f docker-compose.yml up --build
      - name: Remove old image or storage
        run: |
              docker system prune  -y

     
  show: 
      needs: docker-compose
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: show all The images
        run: |
            docker ps 
         

